### ISSUE TITLE
clock-timer overwrite don't work

### ISSUE THREAD

**Issue by J3k4** [rdmtc/node-red-contrib-sun-position#171]
**Describe the bug**
When overwriting or resetting the payload of the clock-timer node, you always get the error:
"Error: Cannot read property 'overwrite' of undefined"

Except at the inputs:
```
{
  "topic":"manual", 
  "payload":false
}
```
and
```
{
  "topic":"overwrite", 
  "payload":false
}
```

**Logs**
```
13 Aug 21:27:06 - [info] [clock-timer:b9ed1e3f.9dac9] TypeError: Cannot read property 'overwrite' of undefined
    at setExpiringOverwrite (/data/node_modules/node-red-contrib-sun-position/nodes/clock-timer.js:106:85)
    at checkTCPosOverwrite (/data/node_modules/node-red-contrib-sun-position/nodes/clock-timer.js:242:17)
    at clockTimerNode._inputCallback (/data/node_modules/node-red-contrib-sun-position/nodes/clock-timer.js:759:35)
    at clockTimerNode.Node._emitInput (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:200:18)
    at Immediate._onImmediate (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:179:33)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
13 Aug 21:27:06 - [error] [clock-timer:b9ed1e3f.9dac9] Error: Cannot read property 'overwrite' of undefined
```
**Screenshots**
<img width="494" alt="Screenshot 2020-08-13 at 18 17 35" src="https://user-images.githubusercontent.com/9286873/90159864-4a041780-dd91-11ea-90af-baaf9cb8cfd7.png">

<img width="1240" alt="Screenshot 2020-08-13 at 18 17 01" src="https://user-images.githubusercontent.com/9286873/90159975-6ef88a80-dd91-11ea-9653-87c9d0590143.png">

**System information (please complete the following information):**
 - Node Version: 1.1.3
 - Node-Red Version: 1.1.3

**Additional context**
here is the flow:
```
[{"id":"a1e7d60c.976b38","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"b9ed1e3f.9dac9","type":"clock-timer","z":"a1e7d60c.976b38","name":"","topic":"","positionConfig":"b750689f.288168","outputs":"1","autoTrigger":false,"autoTriggerTime":"60000","startDelayTime":10000,"storeName":"","overwriteExpire":"3600000","rules":[{"index":0,"name":"","isValid":false,"valid":{},"timeValue":"06:00","timeType":"entered","timeOp":0,"timeOpText":"↥ until","offsetValue":"","offsetType":"none","multiplier":60000,"timeDays":"*","timeMonths":"*","timeOnlyEvenDays":false,"timeOnlyOddDays":false,"timeDateStart":"","timeDateEnd":"","timeMinValue":"","timeMinType":"none","offsetMinValue":"","offsetMinType":"none","multiplierMin":60000,"timeMaxValue":"","timeMaxType":"none","offsetMaxValue":"","offsetMaxType":"none","multiplierMax":60000,"payloadValue":"false","payloadType":"bool","payloadOffsetValue":"","payloadOffsetType":"none","payloadOffsetMultiplier":60000,"payloadFormat":99,"topic":"","validOperandAValue":"","validOperandAType":"none","validOperator":"true","validOperatorText":"is true","validOperandBValue":"","validOperandBType":"num","valid2LogOperator":0,"valid2LogOperatorText":"N/A","valid2OperandAValue":"","valid2OperandAType":"msg","valid2Operator":"true","valid2OperatorText":"is true","valid2OperandBValue":"","valid2OperandBType":"num","description":"<div><i class=\"fa fa-clock-o\" aria-hidden=\"true\"></i> ↥ until <var>06:00</var></div><div><div class=\"indent-payload-text\"><i class=\"fa fa-step-backward\" aria-hidden=\"true\"></i> <span>Payload: </span> <var>false</var></div></div>","timeMinOp":0,"timeMaxOp":0,"importance":0},{"index":1,"name":"","isValid":false,"valid":{},"timeValue":"22:00","timeType":"entered","timeOp":1,"timeOpText":"↧ from","offsetValue":"","offsetType":"none","multiplier":60000,"timeDays":"*","timeMonths":"*","timeOnlyEvenDays":false,"timeOnlyOddDays":false,"timeDateStart":"","timeDateEnd":"","timeMinValue":"","timeMinType":"none","offsetMinValue":"","offsetMinType":"none","multiplierMin":60000,"timeMaxValue":"","timeMaxType":"none","offsetMaxValue":"","offsetMaxType":"none","multiplierMax":60000,"payloadValue":"false","payloadType":"bool","payloadOffsetValue":"","payloadOffsetType":"none","payloadOffsetMultiplier":60000,"payloadFormat":99,"topic":"","importance":0,"validOperandAValue":"","validOperandAType":"none","validOperator":"true","validOperatorText":"is true","validOperandBValue":"","validOperandBType":"num","valid2LogOperator":0,"valid2LogOperatorText":"N/A","valid2OperandAValue":"","valid2OperandAType":"msg","valid2Operator":"true","valid2OperatorText":"is true","valid2OperandBValue":"","valid2OperandBType":"num","description":"<div><i class=\"fa fa-clock-o\" aria-hidden=\"true\"></i> ↧ from <var>22:00</var></div><div><div class=\"indent-payload-text\"><i class=\"fa fa-step-backward\" aria-hidden=\"true\"></i> <span>Payload: </span> <var>false</var></div></div>","timeMinOp":0,"timeMaxOp":0}],"payloadDefault":"true","payloadDefaultType":"bool","payloadDefaultTimeFormat":0,"payloadDefaultOffset":0,"payloadDefaultOffsetType":"none","payloadDefaultOffsetMultiplier":60000,"x":480,"y":280,"wires":[["79932e55.a4172"]]},{"id":"53380497.12490c","type":"inject","z":"a1e7d60c.976b38","name":"mst.resetOverwrite:true","props":[{"p":"resetOverwrite","v":"true","vt":"bool"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":200,"y":180,"wires":[["b9ed1e3f.9dac9"]]},{"id":"79932e55.a4172","type":"debug","z":"a1e7d60c.976b38","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":630,"y":280,"wires":[]},{"id":"f13b3190.26a54","type":"inject","z":"a1e7d60c.976b38","name":"msg.reset:true","props":[{"p":"reset","v":"true","vt":"bool"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":230,"y":220,"wires":[["b9ed1e3f.9dac9"]]},{"id":"c61a5017.cc992","type":"inject","z":"a1e7d60c.976b38","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"resetOverwrite","payload":"true","payloadType":"bool","x":210,"y":140,"wires":[["b9ed1e3f.9dac9"]]},{"id":"5e6c71bf.60159","type":"comment","z":"a1e7d60c.976b38","name":"reset","info":"","x":190,"y":100,"wires":[]},{"id":"de29da24.df8258","type":"inject","z":"a1e7d60c.976b38","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"manual","payload":"true","payloadType":"bool","x":230,"y":340,"wires":[["b9ed1e3f.9dac9"]]},{"id":"a53f66f5.8e3268","type":"inject","z":"a1e7d60c.976b38","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"manual","payload":"false","payloadType":"bool","x":230,"y":380,"wires":[["b9ed1e3f.9dac9"]]},{"id":"ebe26bb9.e344e8","type":"comment","z":"a1e7d60c.976b38","name":"overwrite","info":"","x":200,"y":300,"wires":[]},{"id":"8a394d81.19852","type":"inject","z":"a1e7d60c.976b38","name":"trigger","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"triggerOnly","payload":"","payloadType":"date","x":250,"y":20,"wires":[["b9ed1e3f.9dac9"]]},{"id":"8adab541.3746d8","type":"inject","z":"a1e7d60c.976b38","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"overwrite","payload":"true","payloadType":"bool","x":230,"y":420,"wires":[["b9ed1e3f.9dac9"]]},{"id":"7f434bcf.b3d8e4","type":"inject","z":"a1e7d60c.976b38","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"overwrite","payload":"false","payloadType":"bool","x":220,"y":460,"wires":[["b9ed1e3f.9dac9"]]},{"id":"b750689f.288168","type":"position-config","z":"","name":"loc","isValide":"true","longitude":"0","latitude":"0","angleType":"deg","timeZoneOffset":"99","timeZoneDST":"0","stateTimeFormat":"3","stateDateFormat":"12"}]
```

**Comment by Hypnos3** [comment]
will be fixed with the next Version
