### ISSUE TITLE
Use of week or day number results in internal error.

### ISSUE THREAD

**Issue by samvik** [rdmtc/node-red-contrib-sun-position#310]
**Describe the bug**
The use of week number (or day number, perhaps others) results in internal error. Does not seem to matter what node is used. The stack trace below is produced with the inject node.

![image](https://user-images.githubusercontent.com/4804024/127346463-89516c5c-a6fe-4dfa-8af3-8fbee2094663.png)

28 Jul 15:03:01 - [info] [time-inject:2a9b2c6390b74ec4] Cannot read property 'getFullYear' of undefined
28 Jul 15:03:01 - [info] [time-inject:2a9b2c6390b74ec4] TypeError: Cannot read property 'getFullYear' of undefined
    at Object.getWeekOfYear (/data/node_modules/node-red-contrib-sun-position/nodes/lib/dateTimeHelper.js:333:35)
    at positionConfigurationNode.getPropValue (/data/node_modules/node-red-contrib-sun-position/nodes/position-config.js:1246:30)
    at positionConfigurationNode.getOutDataProp (/data/node_modules/node-red-contrib-sun-position/nodes/position-config.js:845:25)
    at timeInjectNode.node.prepOutMsg (/data/node_modules/node-red-contrib-sun-position/nodes/time-inject.js:603:49)
    at timeInjectNode._inputCallback (/data/node_modules/node-red-contrib-sun-position/nodes/time-inject.js:880:27)
    at /usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:203:26
    at Object.trigger (/usr/src/node-red/node_modules/@node-red/util/lib/hooks.js:149:13)
    at timeInjectNode.Node._emitInput (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:195:11)
    at timeInjectNode.Node.emit (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:179:25)
    at timeInjectNode.Node.receive (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:478:10)
28 Jul 15:03:01 - [error] [time-inject:2a9b2c6390b74ec4] internal error time-inject:Cannot read property 'getFullYear' of undefined

A quick dive into the source code leads me to believe that the msg.ts is used instead of dNow for week number calulcation etc. and in many cases there is no timestamp in the message. See nodes/position-config.js:845. But I have not spent any time in the code base before so I might miss something.

**Screenshots**

**Expected behavior**
No crash, week and day number functions should return correct information.

**System information (please complete the following information):**
28 Jul 15:02:42 - [info] Node-RED version: v2.0.3
28 Jul 15:02:42 - [info] Node.js  version: v14.17.3

**Additional context**
Discovered this while trying to use the even week limitation.

**Comment by Hypnos3** [comment]
In the current development version this is working:
![image](https://user-images.githubusercontent.com/12692680/133003893-e24100f7-a343-4b29-a17b-469d0e025356.png)

**Comment by Hypnos3** [comment]
Is integrated in the 2.0.0-beta and can be installed, see Releases Information.
